project:
  type: website
  output-dir: docs
  resources:
    - assets/**

website:
  title: "Ejercicios de Estadística"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Módulos
        menu:
          - text: Fundamentos
            href: modules/01_fundamentos.qmd
          - text: Probabilidad
            href: modules/02_probabilidad.qmd
          - text: Muestreo
            href: modules/03_muestreo.qmd
          - text: Estimación
            href: modules/04_estimacion.qmd
          - text: Pruebas de Hipótesis
            href: modules/05_pruebas.qmd
          - text: Regresión/ANOVA
            href: modules/06_regresion.qmd
          - text: CEP / SPC
            href: modules/07_spc.qmd


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    smooth-scroll: true
    css: assets/styles.css
    include-in-header:
      text: |
        <script src="assets/scripts.js"></script>
        <script src="https://webr.r-wasm.org/latest/webr.mjs" type="module"></script>
        <script type="module">
          import { WebR } from "https://webr.r-wasm.org/latest/webr.mjs";
          window.webR = new WebR();
          window.webR.init();
        </script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
